# Generated by Django 4.1.5 on 2023-01-25 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economies', '0002_remove_event_economic_model_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicmodel',
            name='economic_model',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='economicmodel',
            name='economic_model_raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='economicmodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='economies.event'),
        ),
    ]
